services:
  _defaults:
    autoconfigure: true

  PiP\ContaoElements\Controller\ContentElement\ContentBoxStart: ~
  PiP\ContaoElements\Controller\ContentElement\ContentBoxStop: ~
  PiP\ContaoElements\Controller\ContentElement\RowStart: ~
  PiP\ContaoElements\Controller\ContentElement\RowStop: ~
